name: Discord Bot 24/7

on:
  schedule:
    - cron: '0 */6 * * *'  # Restart every 6 hours
  workflow_dispatch:       # Manual trigger

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 360   # 6 hours

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Start Discord Bot
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      run: npm start
